import '../globals.css';
import { Metadata } from 'next';
import { Inter } from "next/font/google";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create Next App'
}

const inter = Inter({ subsets: ["latin"] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {children}
      </body>
    </html>
  )
}
